FROM docker.io/library/php:8.3-cli

RUN apt-get update && apt-get install -y unzip git && rm -rf /var/lib/apt/lists/*

COPY --from=docker.io/library/composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app/

RUN composer install --no-interaction --no-progress

CMD ["vendor/bin/phpunit"]
